// supabase/functions/ai-assistant/index.ts
// Supabase Edge Function: ai-assistant
// -----------------------------------------------------------------------------
// The Quest HQ AI assistant backend. Phase 1 implements action "briefing": a
// short, viewer-scoped daily briefing generated by an open-source model
// (Llama 3.3 70B) on Groq's OpenAI-compatible endpoint.
//
// DEPLOY (one-time):
//   1. Create a free account at https://console.groq.com and make an API key.
//   2. Set the function secrets on the PROD project (qqvmcsvdxhgjooirznrj):
//        supabase secrets set GROQ_API_KEY=gsk_xxx
//        supabase secrets set ALLOWED_ORIGINS="https://<your-prod-origin>,http://localhost:5173"
//      (SUPABASE_URL and SUPABASE_ANON_KEY are injected automatically.)
//   3. Deploy:
//        supabase functions deploy ai-assistant
//
// HARDENING:
//   - JWT-verified by default; we additionally require an APPROVED profile.
//   - Task data is fetched under the CALLER'S JWT, so RLS guarantees the model
//     only ever sees tasks the user could already read.
//   - The Groq key never leaves the server. Body size + a best-effort per-user
//     daily cap protect the shared free tier.
// -----------------------------------------------------------------------------

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { buildBriefingContext } from "./lib/context.mjs";
import { shapeBriefing, fallbackBriefing } from "./lib/shape.mjs";
import { validateDraft } from "./lib/draft.mjs";
import { buildDigestContext, shapeDigest, fallbackDigest } from "./lib/digest.mjs";
import { validateAudioPayload, decodeBase64, pickAudioName } from "./lib/transcribe.mjs";

// Provider seam — swap these two lines to move off Groq.
const GROQ_ENDPOINT = "https://api.groq.com/openai/v1/chat/completions";
const GROQ_MODEL = "llama-3.3-70b-versatile";
const GROQ_TRANSCRIBE_ENDPOINT = "https://api.groq.com/openai/v1/audio/transcriptions";
const GROQ_TRANSCRIBE_MODEL = "whisper-large-v3-turbo";

const MAX_PAYLOAD_BYTES = 32 * 1024;
const MAX_CONTEXT_ITEMS = 25;
const DAILY_CAP = 10; // best-effort, per user, per UTC day

// Best-effort in-memory counter. Resets on cold start — a soft guard, not a
// hard quota (the client's per-day cache is the primary limiter).
const usage = new Map<string, { day: string; n: number }>();

const MAX_DRAFT_TEXT = 500;
const DRAFT_DAILY_CAP = 60; // drafting fires more often than the briefing
const draftUsage = new Map<string, { day: string; n: number }>();

const MAX_CHAT_TEXT = 500;      // per message (question + each history turn)
const MAX_CHAT_HISTORY = 6;     // conversation turns kept for context
const MAX_CHAT_TASKS = 200;     // snapshot lines accepted
const CHAT_DAILY_CAP = 100;     // per user, per UTC day
const chatUsage = new Map<string, { day: string; n: number }>();

const DIGEST_DAILY_CAP = 10; // client caches per week, so real volume is tiny
const digestUsage = new Map<string, { day: string; n: number }>();

const TRANSCRIBE_DAILY_CAP = 60;
const transcribeUsage = new Map<string, { day: string; n: number }>();

function corsHeadersFor(req: Request): Record<string, string> {
  const headers: Record<string, string> = {
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Vary": "Origin",
  };
  const allowList = (Deno.env.get("ALLOWED_ORIGINS") ?? "")
    .split(",").map((s) => s.trim()).filter(Boolean);
  if (allowList.length === 0) {
    console.error("[ai-assistant] ALLOWED_ORIGINS is not set — refusing cross-origin responses.");
    return headers;
  }
  const origin = req.headers.get("Origin") ?? "";
  if (allowList.includes(origin)) headers["Access-Control-Allow-Origin"] = origin;
  return headers;
}

function json(req: Request, body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeadersFor(req), "Content-Type": "application/json" },
  });
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeadersFor(req) });
  if (req.method !== "POST") return json(req, { error: "Method not allowed" }, 405);

  try {
    const groqKey = Deno.env.get("GROQ_API_KEY");
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const anonKey = Deno.env.get("SUPABASE_ANON_KEY");
    if (!groqKey) return json(req, { error: "AI service is not configured." }, 503);
    if (!supabaseUrl || !anonKey) return json(req, { error: "Service credentials are not available." }, 503);

    const authHeader = req.headers.get("Authorization") ?? "";
    const callerJwt = authHeader.replace(/^Bearer\s+/i, "").trim();
    if (!callerJwt) return json(req, { error: "Missing authorization." }, 401);

    // Client keyed by the ANON apikey but carrying the caller's JWT in the
    // Authorization header: identity + all queries run under the caller's RLS.
    const userClient = createClient(supabaseUrl, anonKey, {
      global: { headers: { Authorization: `Bearer ${callerJwt}` } },
    });
    const { data: userData, error: userErr } = await userClient.auth.getUser();
    if (userErr || !userData?.user) return json(req, { error: "Not signed in." }, 401);
    const uid = userData.user.id;

    const { data: profile, error: profErr } = await userClient
      .from("profiles").select("approved, member_id").eq("id", uid).single();
    if (profErr || !profile || !profile.approved) return json(req, { error: "Not authorized." }, 403);
    // Tasks are keyed by member id (e.g. "abraham"), not the auth UUID.
    const memberId = profile.member_id || uid;

    const raw = await req.text();
    const isTranscribe = raw.includes('"transcribe"');
    if (!isTranscribe && raw.length > MAX_PAYLOAD_BYTES) {
      return json(req, { error: "Payload too large." }, 413);
    }
    let payload: { action?: unknown };
    try { payload = JSON.parse(raw || "{}"); } catch { return json(req, { error: "Invalid JSON body." }, 400); }
    const action = payload.action;
    if (action !== "briefing" && action !== "draft_task" && action !== "chat" && action !== "weekly_digest" && action !== "transcribe") {
      return json(req, { error: "Unknown action." }, 400);
    }

    // -------- draft_task: natural-language → validated task fields ----------
    if (action === "draft_task") {
      const dday = new Date().toISOString().slice(0, 10);
      const du = draftUsage.get(uid);
      const dn = du && du.day === dday ? du.n : 0;
      if (dn >= DRAFT_DAILY_CAP) return json(req, { error: "Daily draft limit reached." }, 429);
      draftUsage.set(uid, { day: dday, n: dn + 1 });

      const p = payload as { text?: unknown; team?: unknown; companies?: unknown; today?: unknown; types?: unknown; labels?: unknown; projects?: unknown; statuses?: unknown };
      const text = (typeof p.text === "string" ? p.text : "").slice(0, MAX_DRAFT_TEXT).trim();
      const team = Array.isArray(p.team) ? p.team : [];
      const companies = Array.isArray(p.companies) ? p.companies : [];
      const types = Array.isArray(p.types) ? p.types : [];
      const labels = Array.isArray(p.labels) ? p.labels : [];
      const projects = Array.isArray(p.projects) ? p.projects : [];
      const statuses = Array.isArray(p.statuses) ? p.statuses : [];
      const today = typeof p.today === "string" ? p.today : new Intl.DateTimeFormat("en-CA", { timeZone: "America/Phoenix" }).format(new Date());
      const emptyDraft = { assignees: [], company: null, priority: null, due: null, dueTime: null, type: null, label: null, project: null, status: null, remind: null };
      if (!text) return json(req, { ok: true, draft: emptyDraft });

      const names = team.map((t: any) => `${t.id} = ${t.name}`).join("; ");
      const comps = companies.map((c: any) => `${c.id} = ${c.label}`).join("; ");
      const typeList = types.map((t: any) => `${t.id} = ${t.label}`).join("; ");
      const labelList = labels.map((l: any) => `${l.id} = ${l.label}`).join("; ");
      const projList = projects.map((pr: any) => `${pr.id} = ${pr.label}`).join("; ");
      const statusList = statuses.map((s: any) => `${s.id} = ${s.label}`).join("; ");
      const sys = "You extract task fields from a short sentence. Respond ONLY with a JSON object with keys assignees, company, priority, due, dueTime, type, label, project, status, remind. assignees is an ARRAY of ids from the PEOPLE list (include EVERY person named — one or more); company is an id from the COMPANIES list; priority one of low|medium|high|critical; due as YYYY-MM-DD; dueTime as 24h HH:mm; type is an id from the TYPES list; label is an id from the LABELS list; project is an id from the PROJECTS list; status is an id from the STATUSES list. remind is a reminder RELATIVE TO THE DUE DATE, one of: none, at (at due time), 30m, 1h, 1d (30 minutes / 1 hour / 1 day before due) — map phrases like 'remind me an hour before' to 1h, 'the day before' to 1d, 'when it's due' to at; if a reminder is an ABSOLUTE clock time (e.g. '6am tomorrow') that is not one of these offsets, use null. Use [] for assignees and null for other fields not clearly present. Never invent ids.";
      const usr = `Today is ${today}.\nPEOPLE: ${names || "(none)"}\nCOMPANIES: ${comps || "(none)"}\nTYPES: ${typeList || "(none)"}\nLABELS: ${labelList || "(none)"}\nPROJECTS: ${projList || "(none)"}\nSTATUSES: ${statusList || "(none)"}\nSENTENCE: ${text}`;

      let draft = emptyDraft;
      try {
        const res = await fetch(GROQ_ENDPOINT, {
          method: "POST",
          headers: { Authorization: `Bearer ${groqKey}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            model: GROQ_MODEL, temperature: 0, max_tokens: 200,
            response_format: { type: "json_object" },
            messages: [{ role: "system", content: sys }, { role: "user", content: usr }],
          }),
        });
        if (res.ok) {
          const data = await res.json().catch(() => ({}));
          const content = data?.choices?.[0]?.message?.content ?? "{}";
          let parsed: unknown = {};
          try { parsed = JSON.parse(content); } catch { parsed = {}; }
          draft = validateDraft(parsed, { team, companies, types, labels, projects, statuses });
        } else {
          console.error("[ai-assistant] draft provider rejected", { status: res.status });
        }
      } catch (e) {
        console.error("[ai-assistant] draft fetch threw", e);
      }
      return json(req, { ok: true, draft });
    }

    // -------- transcribe: audio → text (feeds draft_task on the client) -----
    if (action === "transcribe") {
      const tday = new Date().toISOString().slice(0, 10);
      const tu = transcribeUsage.get(uid);
      const tn = tu && tu.day === tday ? tu.n : 0;
      if (tn >= TRANSCRIBE_DAILY_CAP) return json(req, { ok: false, error: "Daily voice limit reached. Try again tomorrow." }, 429);
      transcribeUsage.set(uid, { day: tday, n: tn + 1 });

      const v = validateAudioPayload(payload as { audio?: unknown; mime?: unknown });
      if (!v.ok) return json(req, { ok: false, error: v.error }, 400);

      let bytes: Uint8Array;
      try { bytes = decodeBase64(v.audio); }
      catch { return json(req, { ok: false, error: "Invalid audio." }, 400); }
      if (!bytes.length) return json(req, { ok: false, error: "Empty audio." }, 400);

      const form = new FormData();
      form.append("file", new Blob([bytes], { type: v.mime }), pickAudioName(v.mime));
      form.append("model", GROQ_TRANSCRIBE_MODEL);
      form.append("response_format", "json");
      form.append("temperature", "0");

      try {
        const res = await fetch(GROQ_TRANSCRIBE_ENDPOINT, {
          method: "POST",
          headers: { Authorization: `Bearer ${groqKey}` }, // no Content-Type: fetch sets the multipart boundary
          body: form,
        });
        if (!res.ok) {
          console.error("[ai-assistant] transcribe provider rejected", { status: res.status });
          return json(req, { ok: false, error: "Voice is unavailable right now." }, 502);
        }
        const data = await res.json().catch(() => ({}));
        const text = typeof data?.text === "string" ? data.text.trim() : "";
        return json(req, { ok: true, text });
      } catch (e) {
        console.error("[ai-assistant] transcribe fetch threw", e);
        return json(req, { ok: false, error: "Voice is unavailable right now." }, 502);
      }
    }

    // -------- chat: answer questions from the client's task snapshot ---------
    if (action === "chat") {
      const cday = new Date().toISOString().slice(0, 10);
      const cu = chatUsage.get(uid);
      const cn = cu && cu.day === cday ? cu.n : 0;
      if (cn >= CHAT_DAILY_CAP) return json(req, { ok: false, error: "Daily chat limit reached. Try again tomorrow." }, 429);
      chatUsage.set(uid, { day: cday, n: cn + 1 });

      const p = payload as { question?: unknown; history?: unknown; tasks?: unknown; today?: unknown; truncated?: unknown; clock?: unknown; me?: unknown };
      const question = (typeof p.question === "string" ? p.question : "").slice(0, MAX_CHAT_TEXT).trim();
      const history = (Array.isArray(p.history) ? p.history : [])
        .filter((m: any) => m && (m.role === "user" || m.role === "assistant") && typeof m.content === "string")
        .slice(-MAX_CHAT_HISTORY)
        .map((m: any) => ({ role: m.role, content: String(m.content).slice(0, MAX_CHAT_TEXT) }));
      const taskLines = (Array.isArray(p.tasks) ? p.tasks : [])
        .filter((l: any) => typeof l === "string").slice(0, MAX_CHAT_TASKS);
      const clockLines = (Array.isArray(p.clock) ? p.clock : [])
        .filter((l: any) => typeof l === "string").slice(0, 50);
      const me = (typeof p.me === "string" ? p.me : "").slice(0, 80);
      const truncated = p.truncated === true || (Array.isArray(p.tasks) && p.tasks.length > MAX_CHAT_TASKS);
      const today = typeof p.today === "string" ? p.today : new Intl.DateTimeFormat("en-CA", { timeZone: "America/Phoenix" }).format(new Date());
      if (!question) return json(req, { ok: true, answer: "What would you like to know about your tasks?" });

      const sys = `You are a helpful assistant inside a task manager. Answer the user's question using ONLY the information provided below (TASKS, and CLOCKED IN NOW). Never invent tasks, people, dates, companies, or timers. If the answer is not in the provided information, say you don't see it. You cannot create, edit, complete, assign, delete, or clock anything — you only answer questions.${me ? ` The person asking is ${me}.` : ""} Be concise. When you list more than one task, put each on its own line starting with "- " (a hyphen and a space), not in a comma-separated sentence. Do not use markdown headings, tables, or emojis. If the NOTE says the list was truncated, mention your view may be partial.`;
      const clockBlock = clockLines.length ? clockLines.join("\n") : "(nobody you can see is clocked in right now)";
      const taskBlock = `Today is ${today}.${truncated ? "\nNOTE: the task list was truncated; you may not see every task." : ""}\nCLOCKED IN NOW:\n${clockBlock}\nTASKS:\n${taskLines.join("\n") || "(no tasks)"}`;
      const messages = [
        { role: "system", content: sys },
        ...history,
        { role: "user", content: `${question}\n\n${taskBlock}` },
      ];

      try {
        const res = await fetch(GROQ_ENDPOINT, {
          method: "POST",
          headers: { Authorization: `Bearer ${groqKey}`, "Content-Type": "application/json" },
          body: JSON.stringify({ model: GROQ_MODEL, temperature: 0.3, max_tokens: 500, messages }),
        });
        if (!res.ok) {
          console.error("[ai-assistant] chat provider rejected", { status: res.status });
          return json(req, { ok: false, error: "The assistant is unavailable right now." }, 502);
        }
        const data = await res.json().catch(() => ({}));
        const answer = data?.choices?.[0]?.message?.content ?? "";
        if (!answer.trim()) return json(req, { ok: false, error: "No answer was produced." }, 502);
        return json(req, { ok: true, answer });
      } catch (e) {
        console.error("[ai-assistant] chat fetch threw", e);
        return json(req, { ok: false, error: "The assistant is unavailable right now." }, 502);
      }
    }

    // -------- weekly_digest: RLS-scoped done/slipped/coming recap -----------
    if (action === "weekly_digest") {
      const gday = new Date().toISOString().slice(0, 10);
      const gu = digestUsage.get(uid);
      const gn = gu && gu.day === gday ? gu.n : 0;
      if (gn >= DIGEST_DAILY_CAP) return json(req, { error: "Daily digest limit reached. Try again tomorrow." }, 429);
      digestUsage.set(uid, { day: gday, n: gn + 1 });

      const gp = payload as { today?: unknown };
      const today = typeof gp.today === "string" ? gp.today : new Intl.DateTimeFormat("en-CA", { timeZone: "America/Phoenix" }).format(new Date());

      // No assignee filter — RLS bounds the rows to what the caller may read.
      const { data: drows, error: dErr } = await userClient
        .from("tasks")
        .select("id,title,company_id,due,status,priority,assignee_id,completed_at")
        .order("due", { ascending: true })
        .limit(400);
      if (dErr) {
        console.error("[ai-assistant] digest fetch failed", dErr);
        return json(req, { error: "Could not load tasks." }, 500);
      }
      const dtasks = (drows ?? []).map((r: any) => ({
        id: r.id, title: r.title, company: r.company_id, due: r.due,
        status: r.status, completedAt: r.completed_at,
      }));
      const dctx = buildDigestContext(dtasks, { today, windowDays: 7 });

      const dsys = "You are a concise task assistant writing a weekly digest. In 2 to 4 sentences, recap what got done this past week, what slipped, and what is coming in the next 7 days, then up to 3 short bullet lines each naming one specific task. Only reference tasks in the provided context. Plain text, no emojis, no markdown headings.";
      const dusr = `Today is ${today}.\nCounts: ${JSON.stringify(dctx.counts)}\nItems:\n${dctx.lines.join("\n") || "(none)"}`;

      let digest;
      try {
        const res = await fetch(GROQ_ENDPOINT, {
          method: "POST",
          headers: { Authorization: `Bearer ${groqKey}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            model: GROQ_MODEL, temperature: 0.4, max_tokens: 350,
            messages: [{ role: "system", content: dsys }, { role: "user", content: dusr }],
          }),
        });
        if (!res.ok) {
          console.error("[ai-assistant] digest provider rejected", { status: res.status });
          digest = fallbackDigest(dctx);
        } else {
          const data = await res.json().catch(() => ({}));
          const text = data?.choices?.[0]?.message?.content ?? "";
          digest = shapeDigest(text, dctx);
        }
      } catch (e) {
        console.error("[ai-assistant] digest fetch threw", e);
        digest = fallbackDigest(dctx);
      }
      return json(req, { ok: true, digest, generatedAt: new Date().toISOString() });
    }

    // -------- briefing (existing) -----------------------------------------
    // Best-effort per-user daily cap.
    const day = new Date().toISOString().slice(0, 10);
    const u = usage.get(uid);
    const n = u && u.day === day ? u.n : 0;
    if (n >= DAILY_CAP) return json(req, { error: "Daily briefing limit reached. Try again tomorrow." }, 429);
    usage.set(uid, { day, n: n + 1 });

    // ---- fetch the viewer's tasks under RLS -----------------------------
    // Pull a bounded slice of the caller's open + recently-completed tasks.
    // Match on EITHER the lead (assignee_id) or any co-assignee (assignee_ids,
    // migration 060) — filtering on assignee_id alone never even fetched the
    // rows where the caller is a co-assignee, so their briefing silently
    // omitted them. member ids are slugs/UUIDs; the guard keeps the value from
    // breaking out of the PostgREST or() filter grammar.
    const safeMember = /^[A-Za-z0-9_-]+$/.test(memberId) ? memberId : null;
    let taskQuery = userClient
      .from("tasks")
      .select("id,title,company_id,due,status,priority,assignee_id,assignee_ids,focus_seq,completed_at");
    taskQuery = safeMember
      ? taskQuery.or(`assignee_id.eq.${safeMember},assignee_ids.cs.{${safeMember}}`)
      : taskQuery.eq("assignee_id", memberId);
    const { data: rows, error: taskErr } = await taskQuery
      .order("due", { ascending: true })
      .limit(120);
    if (taskErr) {
      console.error("[ai-assistant] task fetch failed", taskErr);
      return json(req, { error: "Could not load your tasks." }, 500);
    }
    const tasks = (rows ?? []).map((r) => ({
      id: r.id, title: r.title, company: r.company_id, due: r.due, status: r.status,
      priority: r.priority, assignee: r.assignee_id,
      assigneeIds: Array.isArray(r.assignee_ids) && r.assignee_ids.length
        ? r.assignee_ids
        : (r.assignee_id ? [r.assignee_id] : []),
      focusSeq: r.focus_seq, completedAt: r.completed_at, activity: [],
    }));

    const today = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Phoenix" }).format(new Date());
    const ctx = buildBriefingContext(tasks, { me: memberId, today, maxItems: MAX_CONTEXT_ITEMS });

    // ---- call Groq ------------------------------------------------------
    const system = "You are a concise task assistant. Write a 2 to 4 sentence briefing describing what happened and what needs attention today, then up to 3 short bullet lines each naming one specific task. Only reference tasks in the provided context. Plain text, no emojis, no markdown headings.";
    const userMsg = `Today is ${today}.\nCounts: ${JSON.stringify(ctx.counts)}\nTasks:\n${ctx.lines.join("\n") || "(none)"}`;

    let briefing;
    try {
      const res = await fetch(GROQ_ENDPOINT, {
        method: "POST",
        headers: { Authorization: `Bearer ${groqKey}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          model: GROQ_MODEL, temperature: 0.4, max_tokens: 350,
          messages: [{ role: "system", content: system }, { role: "user", content: userMsg }],
        }),
      });
      if (!res.ok) {
        console.error("[ai-assistant] provider rejected", { status: res.status });
        // Degrade to a deterministic summary rather than failing the card.
        briefing = fallbackBriefing(ctx);
      } else {
        const data = await res.json().catch(() => ({}));
        const text = data?.choices?.[0]?.message?.content ?? "";
        briefing = shapeBriefing(text, ctx);
      }
    } catch (e) {
      console.error("[ai-assistant] provider fetch threw", e);
      briefing = fallbackBriefing(ctx);
    }

    return json(req, { ok: true, briefing, generatedAt: new Date().toISOString() });
  } catch (err) {
    console.error("[ai-assistant] uncaught", err);
    return json(req, { error: "Internal error." }, 500);
  }
});
