import { chromium } from '@playwright/test';
const PNG='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';
const browser = await chromium.launch({ executablePath: 'C:/Users/tagal/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe' });
const page = await (await browser.newContext({ viewport:{width:440,height:850}, deviceScaleFactor:2 })).newPage();
await page.goto('http://localhost:4173/app.html?preview=1&role=developer&member=abraham', { waitUntil:'networkidle' });
await page.waitForTimeout(900);
await page.evaluate((src)=>{ const a=document.getElementById('userAvatar'); a.style.background='transparent'; const img=document.createElement('img'); img.src=src; img.style.cssText='width:100%;height:100%;border-radius:50%;object-fit:cover;'; a.replaceChildren(img); }, PNG);
await page.waitForTimeout(300);
await page.screenshot({ path:'verify_out/av_fixed.png', clip:{x:0,y:0,width:440,height:60} });
await browser.close();
