import { chromium } from '@playwright/test';
const exe = 'C:/Users/tagal/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe';
const browser = await chromium.launch({ executablePath: exe });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.goto('http://localhost:4188/app.html?preview=1&role=admin&member=abraham', { waitUntil: 'networkidle' });
await page.waitForTimeout(800); await page.keyboard.press('Escape'); await page.waitForTimeout(200);
await page.evaluate(() => App.controller.setView('home'));
await page.waitForTimeout(600);
await page.screenshot({ path: 'verify_out/glass_home.png' });
await page.evaluate(() => App.controller.setView('all'));
await page.waitForTimeout(600);
await page.screenshot({ path: 'verify_out/glass_alltasks.png' });
console.log('ERRS=', errs.length ? errs : 'none');
await browser.close();
