import { chromium } from '@playwright/test';
const exe = 'C:/Users/tagal/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe';
const browser = await chromium.launch({ executablePath: exe });
const page = await (await browser.newContext({ viewport:{width:1280,height:900} })).newPage();
await page.goto('http://localhost:4188/app.html?preview=1&role=admin&member=abraham', { waitUntil:'networkidle' });
await page.waitForTimeout(900); await page.keyboard.press('Escape'); await page.waitForTimeout(300);
await page.evaluate(()=>{ const tm=App.controller.taskModel; tm.all().filter(t=>t.status!=='done'&&t.id!==App.DEFAULT_CLOCK_TASK_ID).slice(0,3).forEach(t=>tm.toggleDone(t.id,'T')); });
await page.evaluate(()=>App.controller.setView('reports'));
await page.waitForTimeout(300);
const rows = await page.$$eval('.qhq-cl-row .ti', els => els.map(e => ({ text: e.textContent, w: Math.round(e.getBoundingClientRect().width), sw: e.scrollWidth })));
console.log(JSON.stringify(rows,null,1));
await browser.close();
