import { chromium } from '@playwright/test';
const exe = 'C:/Users/tagal/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe';
const browser = await chromium.launch({ executablePath: exe });
const page = await (await browser.newContext({ viewport:{width:1280,height:800} })).newPage();
await page.goto('http://localhost:4188/app.html?preview=1&role=developer&member=abraham', { waitUntil:'networkidle' });
await page.waitForTimeout(1000);
await page.keyboard.press('Escape');
await page.waitForTimeout(400);
const tour = await page.locator('.tour-root').count();
console.log('TOUR_PRESENT_AFTER_ESC=', tour);
await page.screenshot({ path:'verify_out/redesign_t3_desktop.png' });
await page.locator('#askQuestBtn').click();
console.log('ASKQUEST_FOCUS=', await page.evaluate(() => document.activeElement && document.activeElement.id));
await page.locator('#userAvatar').click();
await page.waitForTimeout(300);
const onscreen = await page.locator('.user-menu').evaluate(el => { const r=el.getBoundingClientRect(); return r.left>=0 && r.top>=0 && r.bottom<=window.innerHeight && r.right<=window.innerWidth; }).catch(e=>'ERR:'+e.message);
console.log('USERMENU_ONSCREEN=', onscreen);
await page.screenshot({ path:'verify_out/redesign_t3_menu.png' });
await browser.close();
