import { chromium } from '@playwright/test';
const exe = 'C:/Users/tagal/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe';
const browser = await chromium.launch({ executablePath: exe });
const errs = [];
const page = await (await browser.newContext({ viewport:{width:1280,height:800}, deviceScaleFactor:1 })).newPage();
page.on('console', m => { if (m.type()==='error') errs.push(m.text()); });
await page.goto('http://localhost:4188/app.html?preview=1&role=developer&member=abraham', { waitUntil:'networkidle' });
await page.waitForTimeout(1500);
await page.screenshot({ path:'verify_out/redesign_t2_desktop.png' });
const accent = await page.evaluate(() => getComputedStyle(document.body).getPropertyValue('--amber').trim());
const font = await page.evaluate(() => getComputedStyle(document.body).fontFamily);
console.log('ACCENT=', accent);
console.log('FONT=', font);
console.log('CONSOLE_ERRORS=', errs.length ? errs.slice(0,5) : 'none');
await browser.close();
