import { chromium } from '@playwright/test';
const exe = 'C:/Users/tagal/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe';
const browser = await chromium.launch({ executablePath: exe });
const page = await (await browser.newContext({ viewport:{width:1280,height:800} })).newPage();
await page.goto('http://localhost:4188/app.html?preview=1&role=developer&member=abraham', { waitUntil:'networkidle' });
await page.waitForTimeout(900); await page.keyboard.press('Escape'); await page.waitForTimeout(300);
const title0 = await page.locator('#tbTitle').textContent();
await page.locator('#scopeSeg button[data-scope="mine"]').click(); await page.waitForTimeout(150);
const mineOn = await page.locator('.seg button[data-scope="mine"]').evaluate(e=>e.classList.contains('on'));
const titleMine = await page.locator('#tbTitle').textContent();
await page.locator('#scopeSeg button[data-scope="all"]').click(); await page.waitForTimeout(150);
const allOn = await page.locator('.seg button[data-scope="all"]').evaluate(e=>e.classList.contains('on'));
const titleAll = await page.locator('#tbTitle').textContent();
console.log(JSON.stringify({title0, mineOn, titleMine, allOn, titleAll}));
await page.screenshot({ path:'verify_out/redesign_t5.png', clip:{x:248,y:0,width:600,height:60} });
await browser.close();
