import { chromium } from '@playwright/test';
const EXE = 'C:/Users/tagal/AppData/Local/ms-playwright/chromium-1223/chrome-win64/chrome.exe';
const browser = await chromium.launch({ executablePath: EXE });
const page = await (await browser.newContext({ viewport: { width: 1400, height: 1000 } })).newPage();
await page.goto('http://localhost:4173/app.html?preview=1&role=admin&member=abraham', { waitUntil: 'networkidle' });
await page.waitForTimeout(1000); await page.keyboard.press('Escape'); await page.waitForTimeout(300);
const bt = await page.evaluate(() => getComputedStyle(document.querySelector('.side-foot')).borderTopWidth);
console.log('side-foot border-top:', bt);
const el = await page.$('nav .sidebar, nav');
await (await page.$('.side-foot')).screenshot({ path: 'verify_out/sidefoot.png' });
await browser.close();
